config/routes.rb
BcmsNews::Engine.routes.draw do
  
  # This is going to be added under /bcms_news/news/articles.rss
  # Add a routing extension (w/ mount_bcms_news or ), or make a non-isolated engine.
  # Alternatively, just mount as /news rather than /bcms_news then update the match.
  get '/articles/feed', :to=>"news_articles#feed", :defaults => { :format => 'rss' }, :as=>'news_feed'
  
  content_blocks :news_articles 
  
end

app/models/bcms_news/news_article.rb
class BcmsNews::NewsArticle < ActiveRecord::Base
  acts_as_content_block :taggable => true
  
  has_attachment :file
  
  belongs_to :category, :class_name=>"Cms::Category"

  validates_presence_of :name, :release_date
  
  before_validation :set_slug
  
  class << self
    def released
      where(:published => true).where("release_date <= ?", Time.now)
    end
    
    def released_on(date)
      d = if date.kind_of?(Hash)
        Date.new(date[:year].to_i, date[:month].to_i, date[:day].to_i)
      else
        date
      end

      where("release_date >= ? AND release_date < ?", d.beginning_of_day, (d.beginning_of_day + 1.day))
    end  
    
    def with_slug(slug)
      where(:slug => slug)
    end
  end

  def category_name
    category ? category.name : nil
  end
  
  def set_slug
    self.slug = name.to_slug unless name.blank?
  end
  
  def route_params
    {:year => release_date.strftime("%Y"), 
      :month => release_date.strftime("%m"), 
      :day => release_date.strftime("%d"), 
      :slug => slug}
  end
  
  def year
    release_date ? release_date.year : nil
  end

  def month
    release_date ? release_date.month : nil
  end
  
  def set_attachment_section
    if !attachment_file.blank?
      attachment.section = Cms::Section.first(:conditions => {:name => 'News'})
    end
  end
  
  def set_attachment_file_path
    if !attachment_file.blank?
      attachment.file_path = "/news/articles/attachment/#{Time.now.to_s(:year_month_day)}/#{name.to_slug}.#{attachment_file.original_filename.split('.').last.to_s.downcase}" 
    end
  end

end

app/controllers/bcms_news/news_articles_controller.rb
module BcmsNews
  class NewsArticlesController < Cms::ContentBlockController
    
    # Better as something like: allow :guests, :only=>:feed
    skip_filter :redirect_to_cms_site, :only=>:feed
    skip_filter :login_required, :only=>:feed
    skip_filter :cms_access_required, :only=>:feed
      
    # Different method to avoid clashing with the backend content library for this.
    def feed
      @articles = NewsArticle.released.all(:limit => 15, :order => "release_date desc")
    end
  end
end

app/helpers/bcms_news/application_helper.rb
module BcmsNews
  module ApplicationHelper
    
  end
end

app/views/bcms_news/news_articles/_form.html.erb
<%= f.input :name, as: :cms_text_field %>
<%= f.input :release_date, as: :date_picker %>
<%= f.input :category_id, as: :cms_drop_down, categories_for('News Article').map{|c| [c.path, c.id]} %>
<%= f.input :summary, as: :cms_text_area, :style => "height: 100px" %>
<%= f.input :body, as: :text_editor %>
<%= f.input :file, as: :file_picker %>
<%= f.cms_tag_list %>

app/views/bcms_news/news_articles/render.html.erb
<h2><%=h @content_block.name %></h2>
<p><%= @content_block.body.html_safe %></p>
<% if @content_block.file %>
<%= link_to "Attachment", attachment_path_for(@content_block.file) %>
<% end %>

app/views/layouts/templates/default.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title><%= page_title %></title>
    <%= yield :html_head %>
	<%= auto_discovery_link_tag( :rss, bcms_news.news_feed_url, {:title => "RSS Feed for News Articles"}) %>
  </head>
  <body style="margin: 0; padding: 0; text-align: center;">
    <%= cms_toolbar %>
    <div id="wrapper" style="width: 700px; margin: 0 auto; text-align: left; padding: 30px">
      Breadcrumbs: <%= render_breadcrumbs %>
      Main Menu: <%= render_menu %>
      <h1><%= page_title %></h1>
      <%= container :main %>
    </div>
  </body>
</html>

app/views/portlets/news_archive/_form.html.erb
<%= f.cms_text_field :name %>
<%= f.cms_drop_down :category_id, categories_for('News Article').map{|c| [c.path, c.id]}, { :selected=>f.object.category_id.to_i, :include_blank=>"Show News Articles in any Category", :instructions=>"Select a category to show News Articles from only that category." } %>
<%= f.cms_template_editor :template %>

app/views/portlets/news_archive/render.html.erb
<div>
  <% @articles.group_by(&:year).sort_by(&:first).reverse.each do |year, year_articles| %>
    <!-- <%= year %> -->
    <% year_articles.group_by(&:month).sort_by(&:first).reverse.each do |month, month_articles| %>
      <b class="month"><%= Date::MONTHNAMES[month] %></b>
      <% for article in month_articles.sort_by(&:release_date).reverse %>
        <div class="news-item">
          <% unless article.release_date.blank? -%>
            <span class="release-date"><b><%= article.release_date.to_s(:long) %></b></span><br/>
          <% end %>

          <b><%= link_to article.name, news_article_path(article.route_params) %></b><br/>
          <% unless article.summary.blank? -%>
            <p><%= article.summary %></p>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/portlets/news_article/_form.html.erb
<%= f.cms_text_field :name %>
<%= f.cms_template_editor :template %>

app/views/portlets/news_article/render.html.erb
<% if @news_article -%>
  <% page_title @news_article.name %>
  <h2><%=h @news_article.name %></h2>
  <p><%= @news_article.body.html_safe %></p>
<% else -%>
  <b>Missing required parameter</b><br/>
  This portlet expects a request parameter 'news_article_id'. Be sure the calling page provides it.
<% end -%>

app/views/portlets/news_rss/render.xml.erb
xml.instruct! :xml, :version=>"1.0" 
xml.rss(:version=>"2.0") do
  xml.channel do
    xml.title("Articles")
    xml.link("/news/rss")
    xml.description("")
    xml.language('en-us')
      for article in @articles
        xml.item do
          xml.title(article.name)
          xml.description(article.summary) unless article.summary.blank?             
          xml.pubDate(article.release_date.strftime("%a, %d %b %Y %H:%M:%S %z")) unless article.release_date.blank?
          xml.link(news_articles_path(article.details_params))
          xml.guid(news_articles_path(article.details_params))
        end
      end
  end
end

app/views/portlets/recent_news/_form.html.erb
<%= f.cms_text_field :name %>
<%= f.cms_text_field :limit, :label => "Number to show", :size => 2 %>
<%= f.cms_drop_down :sort_by, %w(name release_date).collect { |field| [field.titleize, field] } %>
<%= f.cms_drop_down :sort_order, %w(asc desc).collect { |field| ["#{field.titleize}ending", field.upcase] } %>
<%= f.cms_drop_down :category_id, categories_for('News Article').map{|c| [c.path, c.id]}, {:selected=>f.object.category_id.to_i, :include_blank=>"Show News Articles in any Category", :instructions=>"Select a category to show News Articles from only that category." } %>
<%= f.cms_text_field :more_link %>
<%= f.cms_template_editor :template %>

app/views/portlets/recent_news/render.html.erb
<b>Latest News</b>
<br/>
<br/>

<% for article in @articles %>
  <div class="news-item-browser">
    <% if article.release_date -%>
      <b><%= article.release_date.to_date.to_s(:long) %></b>
      <br/>
    <% end %>
  
    <%= link_to h(article.name), news_article_path(article.route_params) %>
    
  </div>
<% end %>

<% unless @portlet.more_link.blank? -%>
  <div class="news-item-browser">
    <%= link_to "MORE", @portlet.more_link %>
  </div>
<% end %>